---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_zero_port: 8890
  data_bags_path: test/data_bags

platforms:
  - name: centos-6.6

suites:
  - name: default
    driver:
      customize:
        memory: 1536
      network:
        - ["forwarded_port", {guest: 443, host: 4430}]
        - ["forwarded_port", {guest: 4443, host: 4443}]
        - ["private_network", {ip: "192.168.56.100"}]
    run_list:
      - recipe[analytics-workshop::server]

  - name: analytics
    driver:
      customize:
        memory: 1536
      network:
        - ["forwarded_port", {guest: 443, host: 4444}]
        - ["private_network", {ip: "192.168.56.101"}]
    run_list:
      - recipe[analytics-workshop::analytics]
    attributes:
